# -*- coding: utf-8 -*-
"""Escape Character.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W0j3Mur1-frws4GWMe2mfK7TL7QsydQ4
"""

print('Dia berkata : "Pergilah!"')

print("Äku menimpali: \"Äpakah kau ingin aku 'ángkat kaki'?!"\")

print("\\(^_^)/ (\\-_-/)")