# -*- coding: utf-8 -*-
"""Jenis Tipe Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dl8PCVoI7PHnVNvIZmRjDSf-LmKUllOD

Nama : Hanifah Azhar
NPM: 2411012051
"""

nama = 'Fafa'
usia = 20
cantik = True

print(type(nama))
print(type(usia))
print(type(cantik))

usia = input ('Masukkan usia anda: ')

print(type(usia))

a = 10 / 5
print(type(a))

b = 1 / 2
print(type(b))

kata = 'Peach' * 10

print(kata)
print(type(kata))

panjang = int(input('Masukkan panjang: '))
lebar = float(input('Masukkan lebar: '))

print('Luas =', panjang * lebar)

nama = 'Woomin'
tahun_lahir = 2005

print(nama + ' lahir di tahun ' + str(tahun_lahir))