# -*- coding: utf-8 -*-
"""KELOMPOK 11_UTS COMPRO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gr0Ijj7a8zbg-yqoJSg-g6bhlyNZzekq
"""

# DATA AWAL
raw_log = "ID:001#NAMA:kopi susu gula aren#QTY:3#PRICE:18000;ID:002#NAMA:COFFEE LATTE#QTY:1#PRICE:25000"


# PROSES

# 1.SPLITTING
t1, t2 = raw_log.split(";")
t1 = t1.split("#")
t2 = t2.split("#")
# split() digunakan untuk memecah string menjadi beberapa bagian atau list berdasarkan pemisah tertentu seperti tanda (";") dan ("#") di raw log tugas


# 2. CLEANING (PEMBERSIHAN DATA)
nama1 = t1[1].replace("NAMA:", "").strip()
qty1 = t1[2].replace("QTY:", "").strip()
price1 = t1[3].replace("PRICE:", "").strip()

nama2 = t2[1].replace("NAMA:", "").strip()
qty2 = t2[2].replace("QTY:", "").strip()
price2 = t2[3].replace("PRICE:", "").strip()
# replace() digunakan untuk menghapus label seperti "NAMA:", "QTY:", "PRICE:"
# strip() digunakan untuk menghilangkan spasi berlebih di awal dan akhir teks


# 3.TRANSFORMASI & CASTING
nama1 = nama1.title()
nama2 = nama2.title()

qty1 = int(qty1)
price1 = int(price1)

qty2 = int(qty2)
price2 = int(price2)
# title() digunakan untuk mengubah format huruf agar lebih rapi (Title Case)
# int() digunakan untuk mengubah tipe data dari string menjadi integer


# 4.PERHITUNGAN
sub1 = qty1 * price1
sub2 = qty2 * price2
total = sub1 + sub2
# operator (*) untuk menghitung subtotal
# operator (+) untuk menghitung total pendapatan


# 5.OUTPUT
line_eq = "=" * 55
line_dash = "-" * 55

print(line_eq)
print("        LAPORAN HARIAN KEDAI SOU SPACE        ")
print(line_eq)

print("MENU                          QTY     HARGA     SUBTOTAL")
print(line_dash)

print(f"{nama1:<30}{qty1:<8}{price1:<10}{sub1:<10}")
print(f"{nama2:<30}{qty2:<8}{price2:<10}{sub2:<10}")

print(line_dash)
print(f"TOTAL PENDAPATAN HARI INI: Rp {total}")
print(line_eq)
# "=" * 55 dan "-" * 55 digunakan untuk membuat garis pembatas
# print() digunakan untuk menampilkan output
# print(f"...") atau f-string digunakan untuk menggabungkan teks dengan variabel dan mengatur format tabel