# -*- coding: utf-8 -*-
"""Manipulasi String 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eO4WCiEjoBgrdr-6zOr4fxi1wfLbirEv
"""

template = 'Halo, saya %s dari %s'

print(template % ('Noeyya', 'Spanyol'))

template = 'Halo, saya {nama} dari {asal}'
template_2 = 'Saya suka makan {} dan minum {}'

print(template.format(nama = 'Cha Woomin', asal = 'Indonesia'))
print(template_2.format('Nasi Padang', 'Matcha'))

nama = 'Hanifah Azhar'
npm = '2411012051'

print(f'Perkenalkan saya {nama} dari {npm}')

alamat = 'Kotagajah, Lampung Tengah, Indonesia'

print(alamat.split())
print(alamat.split(','))
print(alamat.split(', '))

print('🍅'.join(['i', 'like', 'tomato']))

print('mau apa kamu!'.upper())
print('datang kesini!'.upper())

print('SELAMAT SIANG!'.lower())
print('ADA YANG BISA DIBANTU?'.lower())

print('kapan kita kaya?'.title())

print('Dasar Bahlil'.swapcase())

angka = '12345'

print('Index angka 1:', angka.find('1'))
print('Index angka 45:', angka.find('45'))
print('Index angka 20:', angka.find('20'))

jenjang_pendidikan = 'Kuliah'

print(jenjang_pendidikan.replace('i', 'y'))
print(jenjang_pendidikan.replace('Kul', ''))

paragraf = 'Ditemukan seorang bidadari cantik tergulung di telur gulung bernama Fafa'
x = paragraf.count('di')

print(f'Kata "di" muncul sebanyak {x} kali')