# -*- coding: utf-8 -*-
"""Manipulasi_String.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Op_pDEEy_vA1kH0e-0BOhc1Rj8-xZSXM

**String**
"""

nama = 'Hanifah Azhar'
asal = "Kanada"

print(nama)

print(asal)

"""**Manipulasi String**"""

print(nama, asal)

print(nama + asal)

print("Halo, nama saya", nama)

print("Halo, nama saya", nama, "äsal saya dari", asal)

data_lengkap_aja = nama + asal

print(data_lengkap_aja)

"""**String + Non String**"""

asal_kota = "Bandar Lampung"
kode_pos = 35144

asal_kota_kode_pos = asal_kota + str(kode_pos)

print(asal_kota_kode_pos)

asal_kota_x3 = asal_kota * 3

print(asal_kota_x3)