# -*- coding: utf-8 -*-
"""Manipulasi String 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FVRWHZImQse-gsW4h7H5TWTtiBSDmE40

**Operasi In Pada String**
"""

berita = 'Banyak programmer di berbagai negara mulai memakai \
editor teks seperti Visual Studio Code, \
Atom, dan lainnya.'

print('Visual Studio Code' in berita)
print('Notepad++' in berita)

"""**Memotong String (Indexing)**"""

nama = 'Cha Woomin'

print(nama[4])
print(nama[8])
print(nama[-1])
print(nama[-5])

"""**Slicing String**"""

judul = 'Pikiran yang matang'

print(judul[0:8])
print(judul[7:14])
print(judul[15:20])
print(judul[:-6])
print(judul[-5:])

"""**Menghitung Panjang String**"""

print(len('Indonesia'))
print(len('Spanish'))

"""**Memeriksa Karakter Awal String**"""

nomor_telepon_1 = '082180492246'
nomor_telepon_2 = '6282180492246'
nomor_telepon_3 = '+6282180492246'

kode_negara = '+62'
print(nomor_telepon_1.startswith(kode_negara))
print(nomor_telepon_2.startswith(kode_negara))
print(nomor_telepon_3.startswith(kode_negara))

"""**Memeriksa Karakter Akhir String**"""

email_1 = 'sawitt@gmail.com'
email_2 = 'sawitt@yahoo.com'

print(email_1.endswith('gmail.com'))
print(email_2.endswith('gmail.com'))